# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_data',
            fields=[
                ('email', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('noi', models.CharField(blank=True, max_length=200, null=True)),
                ('Mobile', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
