# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_add_data_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
