# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_data',
            old_name='user_id',
            new_name='user',
        ),
    ]
