# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('no_cases', models.SmallIntegerField(default=1)),
                ('symptoms', models.CharField(max_length=256)),
                ('prob_cause', models.CharField(max_length=256)),
                ('doc_response', models.CharField(max_length=256)),
                ('cur_sit', models.CharField(max_length=256)),
                ('rel_reports', models.FileField(upload_to=b'./reports')),
                ('loc_response', models.CharField(max_length=256)),
            ],
        ),
    ]
