# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgot_data',
            old_name='user_id',
            new_name='user',
        ),
    ]
